services:
  caddy:
    image: caddy:2.7.6
    container_name: caddy
    restart: always  
    networks:
      - headscale
    ports:
      - 80:80
      - 443:443
    volumes:  
      - ./etc/Caddyfile:/etc/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
networks:
  headscale:
    driver: bridge      
