services:
  caddy:
    build: .
    container_name: caddy
    restart: always  
    networks: headscale
    ports:
      - 80:80
      - 443:443
    volumes:  
      - ./etc/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
networks:
  headscale:
    driver: bridge      
