services:
  caddy:
    image: abiosoft/caddy
    container_name: caddy
    restart: always  
    networks:
      - headscale
    ports:
      - 80:80
      - 443:443
    volumes:  
      - ./etc/Caddyfile:/etc/Caddyfile
      - ./caddycerts:/etc/caddycerts
    environment:
      - CADDYPATH=/etc/caddycerts