services:  
  headscale:  
    image: headscale/headscale:0.25.1
    container_name: headscale
    restart: always  
    network_mode: bridge
    ports:  
      - "8080:8080"  
      - "9090:9090"  
    volumes:  
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
    command: ["headscale", "serve"] 
    environment:
      - TZ=Asia/Shanghai