services:  
  headscale:  
    image: headscale/headscale:0.22.3
    container_name: headscale
    restart: always  
    networks:
      - headscale
    ports:  
      - "8080:8080"  
      - "9090:9090"  
    volumes:  
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
    command: ["serve"] 
    environment:
      - TZ=Asia/Shanghai
networks:
  headscale:
    driver: bridge      