services:
  headscale-admin:
    image: headscale-admin:latest
    container_name: headscale-admin
    restart: always  
    ports:
      - "4567:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - HEADSCALE_API_URL=http://headscale:8080
      - HEADSCALE_API_KEY=your_api_key_here
    networks:
      - headscale

networks:
  headscale:
    driver: bridge      